name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Indica que se usará un runner self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Clear existing files but keep cvs folder
      run: |
        rsync -a --delete --exclude 'storage/app/public/cvs' /home/nmarin/www/ecomuseo/ /home/nmarin/www/ecomuseo_backup/
        rsync -a --delete /home/nmarin/www/ecomuseo_backup/ /home/nmarin/www/ecomuseo/
        rm -rf /home/nmarin/www/ecomuseo_backup/
    
    - name: Copy files to server
      run: |
        cp -r ./* /home/nmarin/www/ecomuseo/
    
    - name: Create validation directory and copy validation file
      run: |
        mkdir -p /home/nmarin/www/ecomuseo/public/.well-known/pki-validation
        cp /home/nmarin/ssl/.well-known/pki-validation/DBCD700D28E5DA5A21A3DDC214A919C2.txt /home/nmarin/www/ecomuseo/public/.well-known/pki-validation/
    
    - name: Install PHP Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        composer install
    
    - name: Install Node.js Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        npm install
    
    - name: Build Assets
      run: |
        cd /home/nmarin/www/ecomuseo
        npm run build
    
    # - name: Run Migrations and Seed Database
    #   run: |
    #     cd /home/nmarin/www/ecomuseo
    #     php artisan migrate:fresh --seed --force
    
    - name: Clear and Cache Configurations
      run: |
        cd /home/nmarin/www/ecomuseo
        php artisan config:clear
        php artisan cache:clear
        php artisan config:cache
