name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Indica que se usará un runner self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
  
    - name: Clear existing files
      run: |
        rm -rf /home/nmarin/www/ecomuseo/*
    - name: Copy files to server
      run: |
        cp -r ./* /home/nmarin/www/ecomuseo/
    - name: Install PHP Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        composer install
    - name: Install Node.js Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        npm install
    - name: Build Assets
      run: |
        cd /home/nmarin/www/ecomuseo
        npm run build
    - name: Run Migrations and Seed Database
      run: |
        cd /home/nmarin/www/ecomuseo
        php artisan migrate:fresh --seed --force
    - name: Set Permissions for storage and cache directories
      run: |
        chmod -R 775 /home/nmarin/www/ecomuseo/storage
        chmod -R 775 /home/nmarin/www/ecomuseo/bootstrap/cache
        chown -R $(whoami):$(whoami) /home/nmarin/www/ecomuseo/storage
        chown -R $(whoami):$(whoami) /home/nmarin/www/ecomuseo/bootstrap/cache
    - name: Configure Laravel on server
      run: |
        cd /home/nmarin/www/ecomuseo
        php artisan config:cache
