name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Indica que se usará un runner self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear existing files except storage and bootstrap/cache
        run: |
          find /var/www/ecomuseo/ -mindepth 1 -maxdepth 1 ! -name 'storage' ! -name 'bootstrap' -exec rm -rf {} +
          find /var/www/ecomuseo/storage -mindepth 1 -exec rm -rf {} +
          find /var/www/ecomuseo/bootstrap/cache -mindepth 1 -exec rm -rf {} +

      - name: Install Dependencies
        run: |
          composer install

      - name: Run Migrations and Seed Database
        run: |
          php artisan migrate:fresh --seed

      - name: Build Assets
        run: |
          npm run build

      - name: Copy files to server
        run: |
          cp -r ./* /var/www/ecomuseo/

      - name: Configure Laravel on server
        run: |
          cd /var/www/ecomuseo
          php artisan config:cache
          php artisan route:cache
          php artisan optimize
