name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Indica que se usará un runner self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clear existing files
        run: |
          rm -rf /home/nrodas/www/ecomuseo/*

      - name: Copy files to server
        run: |
          cp -r ./* /home/nrodas/www/ecomuseo/

      - name: Install PHP Dependencies
        run: |
          cd /home/nrodas/www/ecomuseo
          composer install

      - name: Install Node.js Dependencies
        run: |
          cd /home/nrodas/www/ecomuseo
          npm install

      - name: Build Assets
        run: |
          cd /home/nrodas/www/ecomuseo
          npm run build

      - name: Run Migrations and Seed Database
        run: |
          cd /home/nrodas/www/ecomuseo
          php artisan migrate:fresh --seed --force

      - name: Configure Laravel on server
        run: |
          cd /home/nrodas/www/ecomuseo
          php artisan config:cache
          php artisan route:cache
