name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted  # Indica que se usará un runner self-hosted
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Move files to tmp
      run: |
        mkdir -p /home/nmarin/tmp
        mv /home/nmarin/www/ecomuseo/storage/app/public/cvs/* /home/nmarin/tmp/
    
    - name: Clear existing files
      run: |
        rm -rf /home/nmarin/www/ecomuseo/*

    - name: Copy files to server
      run: |
        cp -r ./* /home/nmarin/www/ecomuseo/

    - name: Create cvs directory
      run: |
        mkdir -p /home/nmarin/www/ecomuseo/storage/app/public/cvs

    - name: Move files back to new cvs directory
      run: |
        mv /home/nmarin/tmp/* /home/nmarin/www/ecomuseo/storage/app/public/cvs/
    
    - name: Create validation directory and copy validation file
      run: |
        mkdir -p /home/nmarin/www/ecomuseo/public/.well-known/pki-validation
        cp /home/nmarin/ssl/.well-known/pki-validation/5C7BD47E624AE4211AD980F7154A03DD.txt /home/nmarin/www/ecomuseo/public/.well-known/pki-validation/
    
    - name: Install PHP Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        composer install
    
    - name: Install Node.js Dependencies
      run: |
        cd /home/nmarin/www/ecomuseo
        npm install
    
    - name: Build Assets
      run: |
        cd /home/nmarin/www/ecomuseo
        npm run build
    
    # - name: Run Migrations and Seed Database
    #   run: |
    #     cd /home/nmarin/www/ecomuseo
    #     php artisan migrate:fresh --seed --force
    
    - name: Clear and Cache Configurations
      run: |
        cd /home/nmarin/www/ecomuseo
        php artisan config:clear
        php artisan cache:clear
        php artisan config:cache
